name: mywitti
description: "Application de fidélité et de gestion de jetons - MyWitti"

# Empêche la publication accidentelle sur pub.dev
publish_to: 'none'

# Version de l'application
# Format: version+build_number (ex: 1.0.0+1)
version: 1.0.0+1

# Environnement Flutter requis
environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

# Dépendances principales
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Icons iOS style
  cupertino_icons: ^1.0.6
  
  # Fonts Google (Poppins, Inter, Roboto)
  google_fonts: ^6.1.0
  
  # Navigation et routing
  go_router: ^12.1.3
  
  # Gestion d'état
  flutter_bloc: ^8.1.3
  
  # Storage local
  shared_preferences: ^2.2.2
  
  # HTTP requests (pour futures API calls)
  dio: ^5.3.2
  
  # Dates et formatage
  intl: ^0.20.2  # ✅ Compatible avec flutter_localizations
  
  # Animations
  flutter_animate: ^4.2.0
  
  # Charts pour les graphiques de tendances
  fl_chart: ^0.64.0

# Dépendances de développement
dev_dependencies:
  flutter_test:
    sdk: flutter

  # Lints pour bonnes pratiques
  flutter_lints: ^3.0.0
  
  # Tests
  mockito: ^5.4.2
  bloc_test: ^9.1.5

# Configuration Flutter
flutter:
  # Active Material Design
  uses-material-design: true
  
  # Configuration Android
  generate: true

  # Assets (images, icons, etc.)
  assets:
    - assets/images/
    - assets/images/categories/
    - assets/icons/
    - assets/animations/

  # Fonts personnalisées (optionnel si Google Fonts suffit)
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Poppins-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700

# Métadonnées du projet
repository: https://github.com/votre-entreprise/mywitti
homepage: https://votre-site.com
documentation: https://docs.votre-site.com

# Informations sur l'équipe (optionnel)
author: Équipe MyWitti <dev@mywitti.com>